'use strict';
// Add a chapter here and a matching animation handler in app.js for future moments.
const STORY = [
 {id:'welcome',chapter:'DUDU HAS A QUESTION',eyebrow:'PSST… BUBUUU!',title:'Do you want to see<br>a <em>special gift</em><br>for you?',description:'Dudu has been keeping a little secret…',button:'YES',hint:'Someone is very excited to show you something.',duration:6000,caption:'',alt:'Dudu stands alone, smiling and asking if you want to see a special gift.'},
 {id:'distance',chapter:'JUST A TINY DISTANCE PROBLEM',eyebrow:'USA · AUSTRALIA',title:'My heart keeps<br>running to <em>you.</em>',description:'Apparently, geography has other plans. Rude.',button:'That voice I love',hint:'Even an ocean can’t stop this little heart.',duration:7400,caption:'',alt:'Dudu runs from the left and Bubu from the right. Both bump into invisible borders and tumble onto their bottoms. USA appears for Dudu, Australia for Bubu. A heart crosses the distance.'},
 {id:'chatter',chapter:'MY FAVORITE VOICE',eyebrow:'AND THEN… AND THEN… AND THEN…',title:'Tell me<br><em>everything.</em>',description:'Every tiny detail. Every plot twist. Even the story with seven side stories.',button:'And then we go outside',hint:'Your voice is one of my favorite places to be.',duration:7900,caption:'A missed reply. A tiny pout. One hug. And the stories continue.',alt:'Bubu talks excitedly while Dudu gets distracted. She puffs her cheeks and folds her arms. Dudu hugs her, she smiles, and she immediately starts chatting again.'},
 {id:'coffee',chapter:'THE COFFEE SHOP PLOT TWIST',eyebrow:'AT HOME VS. EVERYWHERE ELSE',title:'My little<br><em>chatterbox.</em>',description:'A thousand words with me. One tiny whisper at the coffee counter.',button:'A special delivery',hint:'“Dudu… can you order mine?”',duration:7600,caption:'At home: endless stories. At the café: a shy little tap-tap.',alt:'Bubu chatters at home, then sees a coffee counter. She hides behind Dudu, looks down and gently taps both index fingertips together. Dudu orders their coffee, and she starts talking again as they leave.'},
 {id:'parcel',chapter:'EXPRESS DELIVERY',eyebrow:'CONTENTS: AN UNREASONABLE AMOUNT OF LOVE',title:'Too much love.<br>Too little <em>box.</em>',description:'I tried to send a normal-sized birthday hug. Things got slightly out of hand.',button:'Make your birthday wish',hint:'Special delivery for Bubuuu. Handle with hugs.',duration:7400,caption:'One tiny box was never going to hold all this love.',alt:'Dudu pushes a giant heart into a tiny pink parcel, sits on the lid, and it springs open. The heart travels to Bubu in Australia and showers her in love.'},
 {id:'birthday',chapter:'MAKE A LITTLE WISH',eyebrow:'HAPPY BIRTHDAY, BUBUUU',title:'Close your eyes.<br>Make a <em>wish.</em>',description:'Something big. Something tiny. Something only you know. Your birthday wish is waiting below.',button:'Three little things',hint:'No microphones. Just a little birthday magic.',duration:7200,caption:'Today, this little corner of the world is all yours.',alt:'Dudu and Bubu come together, hug, and reveal a strawberry birthday cake with one candle.'},
 {id:'notes',chapter:'THREE LITTLE THINGS',eyebrow:'IN CASE YOU NEED A REMINDER',title:'You mean<br><em>so much to me.</em>',description:'A few little thoughts, tucked away just for you. Tap each one.',button:'One last thing for you',hint:'Some things deserve to be said more often.',duration:6000,caption:'All these little things. All this love.',alt:'Bubu and Dudu hold big pink hearts for each other.'},
 {id:'hug',chapter:'ONE MORE BIRTHDAY HUG',eyebrow:'JUST FOR YOU, BUBUUU',title:'One more hug.<br>Just for <em>you.</em>',description:'Birthday hugs are unlimited here. Come back for one whenever you miss me.',button:'Send me another hug',hint:'You can come back to this little corner of love anytime.',duration:6000,caption:'Until the next real hug. And all the ones after that.',alt:'Bubu and Dudu share a quiet, happy hug.'}
];
